### ISSUE TITLE
Readme example code fails to create index for an "invalid index params" error

### ISSUE THREAD

**Issue by ildella** [milvus-io/milvus-sdk-node#162]
**Describe the bug:**
Following the README code, the `await client.createIndex({...` fails with an `invalid index params` error. 

**Steps to reproduce:**

1. follow the whole README 
2. run the code

the createIndex returns this:

```
      {
        error_code: 'UnexpectedError',
        reason: 'invalid index params: map[dim:128 index_type:HNSW metric_type:L2]',
        code: 0
      }
```

And then the following command, `client.loadCollectionSync({collection_name})` fails with:

```
    ErrorCode: UnexpectedError. Reason: index doesn't exist, collectionID 441604979289427265
```

**Milvus-node-sdk version:**
2.2.10

**Milvus version:**
v2.2.8

**Comment by nameczz** [comment]
@ildella Hi, we got some error on our readme.
![image](https://github.com/milvus-io/milvus-sdk-node/assets/20559208/60bd2636-5956-4a94-a3cc-b36d2456bcae)
param: { efConstruction: 5, M: 4 } should be params: { efConstruction: 10, M: 4 }.
Because of efConstruction rang [8,512].

We will fix it soon. Thanks

**Comment by ildella** [comment]
it worked ;)
