### ISSUE TITLE
Uncaught TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by evanlong0926** [milvus-io/milvus-sdk-node#195]
**Describe the feature:**
- Nuxt3
- NuxtPlugins

**Describe a specific use case for the feature:**

```ts
/plugins/milvus.ts

import { MilvusClient } from '@zilliz/milvus2-sdk-node';

export default defineNuxtPlugin((nuxtApp) => {
  const config = useRuntimeConfig();

  const milvusClient = new MilvusClient({
    address: config.public.milvusHost,
    ssl: false,
  });

  nuxtApp.provide('milvus', milvusClient);
});

declare module '#app' {
  interface NuxtApp {
    $milvus: MilvusClient;
  }
}

declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    $milvus: MilvusClient;
  }
}
```

**Comment by shanghaikid** [comment]
Thanks for reporting, let me try it later.

**Comment by shanghaikid** [comment]
I am not a nuxt expert, according to its documentation, I tried two way to use milvus node sdk. 

- try to create a server api, then call useFetch(worked) 
- try to build a plugin that get called in the page (failed just like you) 

I think because node sdk are using GRPC to communicate with the milvus cluster, so that's impossible call it directly from the browser.  You have to create server api to use it.

**Comment by evanlong0926** [comment]
Thank you very much, I followed your method to solve 🙌.
